SSHcom/privx-kube

charts/privx/Chart.yaml
charts/privx/values.yaml

- use public.ecr.aws/sshprivx registry address
- upgrade privx minor chart version to 0.0.4

fix public repo alias

---

README.md
charts/privx/Chart.yaml
charts/privx/configs/privx/settings/docker_installer_env
charts/privx/configs/privx/settings/shared-config.toml
charts/privx/values.yaml
values-overrides/privx.yaml

- make database and privx credentials as mandatory and configurable.

add db and privx credentials overriding

---

README.md

- Fix the link to the ingress controller link 
- Merge to privx_21 branch

UPD [README] fix bitnami ingress controller link

---

README.md

- fixes migration link to point to privx 22

UPD [README] fix migration link

---

charts/privx/migrations/26/configs/nginx/privx-common.conf
charts/privx/migrations/26/configs/nginx/privx-csp.conf
charts/privx/migrations/26/configs/nginx/privx-https-location-client-cert.conf
charts/privx/migrations/26/configs/nginx/privx-https-location.conf
charts/privx/migrations/26/configs/nginx/privx-proxy-headers.conf
charts/privx/migrations/26/configs/nginx/privx.conf
charts/privx/migrations/26/stage2.yaml
charts/privx/values.yaml

- re-add nginx configurations when upgrading privx so that latest changes are taken in to use
- bigger proxy buffer size is also added to the nginx ingress endpoint so that the ingress controller is not the bottleneck

fixes for OIDC

---

charts/privx/migrations/26/configs/nginx/privx-common.conf
charts/privx/migrations/26/configs/nginx/privx-csp.conf
charts/privx/migrations/26/configs/nginx/privx-https-location-client-cert.conf
charts/privx/migrations/26/configs/nginx/privx-https-location.conf
charts/privx/migrations/26/configs/nginx/privx-proxy-headers.conf
charts/privx/migrations/26/configs/nginx/privx.conf
charts/privx/migrations/26/stage2.yaml
charts/privx/values.yaml

- nginx configs added to upgrade so the latest is used
- proxy buffer size is added to the nginx ingress resource as well

v26 fixes for OIDC

---

charts/privx/Chart.yaml
charts/privx/migrations/26/restore.yaml
charts/privx/migrations/26/stage1.yaml
charts/privx/migrations/26/stage2.yaml
charts/privx/values.yaml
values-overrides/ingress-secure.yaml

- Tested fresh install and upgrade from 25

upgrade to 26.2

---

charts/privx/Chart.yaml
charts/privx/migrations/27/README.md
charts/privx/migrations/27/restore.yaml
charts/privx/migrations/27/stage1.yaml
charts/privx/migrations/27/stage2.yaml
charts/privx/values.yaml
values-overrides/ingress-secure.yaml

- tested both new installation and upgrade from 26.2

UPD [privx] upgarde to 27.1

---

charts/privx/Chart.yaml
charts/privx/configs/privx/templates/role-store.toml_template
charts/privx/migrations/28/configs/new/role-store.toml_template

FIX [kube] role-store data version

---

charts/privx/Chart.yaml
charts/privx/configs/privx/templates/monitor-service.toml_template
charts/privx/migrations/28/configs/new/monitor-service.toml_template

fix monitor service data version

---

charts/privx/Chart.yaml
charts/privx/configs/privx/templates/monitor-service.toml_template
charts/privx/migrations/28/configs/new/monitor-service.toml_template

FIX [privx] monitor service data version

---

charts/privx/Chart.yaml
charts/privx/migrations/30/restore.yaml
charts/privx/migrations/30/stage1.yaml
charts/privx/migrations/30/stage2.yaml
charts/privx/values.yaml

- upgrade migration and privx images to 30.1

UPD [privx] upgrade privx images to 30.1

---

charts/privx/Chart.yaml
charts/privx/migrations/29/restore.yaml
charts/privx/migrations/29/stage1.yaml
charts/privx/migrations/29/stage2.yaml
charts/privx/values.yaml

- upgrade 29 to use 29.1 images

UPD [privx] upgrade privx images to 29.1

---

charts/privx/Chart.yaml
charts/privx/templates/rolebinding.yaml

Fixes the [issue](https://github.com/SSHcom/privx-kube/issues/65)

fix role binding typo

---

charts/privx/migrations/32/restore.yaml
charts/privx/migrations/32/stage1.yaml
charts/privx/migrations/32/stage2.yaml
charts/privx/values.yaml

I have tested the installation, upgrade and rollback.

UPD [privx] upgrade privx to 32.1

---

charts/privx/Chart.yaml

Update Chart version and APP version for main

update Chart version and APP version

---

charts/privx/Chart.yaml
charts/privx/configs/privx/settings/ssh-algorithms.toml
charts/privx/migrations/30/configs/new/ssh-algorithms.toml_template
charts/privx/migrations/30/restore.yaml
charts/privx/migrations/30/stage1.yaml
charts/privx/migrations/30/stage2.yaml
charts/privx/values.yaml

I have tested the rollback, upgrade, installation for privx-kube.30.3

UPD [privx] upgrade privx to 30.3

---

charts/privx/Chart.yaml
charts/privx/configs/privx/settings/ssh-algorithms.toml
charts/privx/migrations/31/configs/new/ssh-algorithms.toml_template
charts/privx/migrations/31/restore.yaml
charts/privx/migrations/31/stage1.yaml
charts/privx/migrations/31/stage2.yaml
charts/privx/values.yaml

I have tested the upgrade, rollback, and installation for privx-kube.31.2

UPD [privx] upgrade privx to 31.2

---

charts/privx/Chart.yaml
charts/privx/configs/privx/settings/ssh-algorithms.toml
charts/privx/migrations/32/configs/new/ssh-algorithms.toml_template
charts/privx/migrations/32/restore.yaml
charts/privx/migrations/32/stage1.yaml
charts/privx/migrations/32/stage2.yaml
charts/privx/values.yaml

I have tested the upgrade, rollback and installation.

UPD [privx] upgrade privx to 32.2

---

charts/privx/migrations/36/README.md

* Add in the restore instructions that `PREVIOUS_VERSION` will be set.

doc(restore): set the previous version

---

charts/privx/migrations/36/README.md

Update README.md for PrivX 36.2

---

charts/privx/migrations/37/README.md

Update README.md for PrivX 37.0
